import type { Metadata } from "next";
import PageHero from "@/components/PageHero";

export const metadata: Metadata = {
  title: "Terms of Service — TallyLine",
  description: "The terms that govern use of TallyLine's voice ledger, credit scoring, and loan-matching services.",
};

const sections = [
  {
    title: "1. Acceptance of these terms",
    body: [
      "By calling the TallyLine number, sending a voice note to our WhatsApp line, or otherwise using the TallyLine service, you agree to these terms.",
    ],
  },
  {
    title: "2. Description of the service",
    body: [
      "TallyLine is a voice-AI bookkeeping service that transcribes spoken sales and expense entries into a digital ledger, and, for traders who opt in, uses that ledger to build a credit score and match traders with partner microfinance lenders.",
      "TallyLine is currently in private beta. Features, languages supported, and availability may change as the product develops.",
    ],
  },
  {
    title: "3. Eligibility",
    body: [
      "The service is intended for individual traders, vendors, and market cooperatives operating primarily in our launch markets of Nigeria and Ghana.",
      "You must provide a working phone number or WhatsApp account to use the service, and be legally able to enter a loan agreement if you use the credit-matching tier.",
    ],
  },
  {
    title: "4. Ledger accuracy",
    body: [
      "Our speech-to-text and entity-extraction models are highly accurate but not perfect, particularly for unusual product names, background noise, or unclear speech. You are responsible for reviewing your ledger and flagging any entry that looks wrong.",
      "TallyLine is not liable for financial decisions made solely on the basis of an unreviewed, incorrect ledger entry.",
    ],
  },
  {
    title: "5. Credit scoring and loan matching",
    body: [
      "TallyLine is not a lender. Our credit score and loan-matching feature connects eligible traders with independent, partner microfinance institutions; all loan terms, approvals, and repayment obligations are set by that partner, not by TallyLine.",
      "A credit score generated by TallyLine does not guarantee loan approval from any partner lender.",
      "You can use the free voice ledger without ever opting into credit scoring or lender data sharing.",
    ],
  },
  {
    title: "6. Fees",
    body: [
      "The basic voice ledger is free to use.",
      "Access to the credit score and loan-matching tier may involve a subscription fee, a commission paid by the partner lender upon a successful loan match, or both, as described at the time you opt in.",
      "Microfinance institutions accessing TallyLine's credit data via our B2B API do so under a separate commercial agreement.",
    ],
  },
  {
    title: "7. Acceptable use",
    body: [
      "You agree not to use TallyLine to log fraudulent transactions, impersonate another trader, or attempt to manipulate the credit-scoring model.",
      "We may suspend an account showing a clear pattern of fraudulent or abusive use.",
    ],
  },
  {
    title: "8. Data and privacy",
    body: [
      "Our collection and use of your voice recordings, transcripts, and ledger data is described in our Privacy Policy, which forms part of these terms.",
    ],
  },
  {
    title: "9. Beta program disclaimer",
    body: [
      "As a private beta product, TallyLine is provided without an uptime guarantee or service-level agreement. Voice transcription, ledger updates, or credit scoring may occasionally be delayed or unavailable while we improve the service.",
    ],
  },
  {
    title: "10. Limitation of liability",
    body: [
      "TallyLine is provided \"as is\" during this beta period. To the fullest extent permitted by law, TallyLine is not liable for indirect, incidental, or consequential damages arising from use of the service, including losses related to loan decisions made by partner lenders.",
    ],
  },
  {
    title: "11. Termination",
    body: [
      "You may stop using TallyLine at any time. We may suspend or close an account for acceptable-use violations, suspected fraud, or as required by a partner lender's compliance obligations.",
    ],
  },
  {
    title: "12. Governing law",
    body: [
      "These terms are governed by the laws of the Federal Republic of Nigeria for users onboarded in Nigeria, and by the laws of the Republic of Ghana for users onboarded in Ghana, without regard to conflict-of-law principles.",
    ],
  },
  {
    title: "13. Changes to these terms",
    body: [
      "We may update these terms as the product evolves. Continued use of TallyLine after an update constitutes acceptance of the revised terms.",
    ],
  },
  {
    title: "14. Contact",
    body: ["Questions about these terms can be sent to hello@tallyline.africa."],
  },
];

export default function TermsPage() {
  return (
    <>
      <PageHero eyebrow="Legal" title="Terms of Service" body="Last updated: July 2026" />
      <section className="py-16 px-6 max-w-3xl mx-auto flex flex-col gap-10">
        {sections.map((s) => (
          <div key={s.title}>
            <h2 className="text-lg font-semibold text-ink mb-4">{s.title}</h2>
            <ul className="flex flex-col gap-3">
              {s.body.map((line) => (
                <li key={line} className="text-sm text-ink-light leading-relaxed">
                  {line}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </section>
    </>
  );
}
